#!/usr/bin/python
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: © 2024-present  Gene C <arch@sapience.com>
"""
Display memory usage for process(es)
"""
# pylint: disable=invalid-name
from lib import ProcInfo
def main() :
    """
    Get process info for process(es)
     - Optional input is process name(s)
    """
    proc_info = ProcInfo()
    proc_info.show_info()

if __name__ == '__main__':
    main()
