#!/usr/bin/bash
#
# Source code checks.
#
mod_dir="src/process_mem"
PYTHONPATH=$(/usr/bin/realpath ./src)

/usr/bin/pylint $mod_dir/*y $mod_dir/*/*py
/usr/bin/pycodestyle --max-line-length=110 $mod_dir/*y $mod_dir/*/*py
/usr/bin/mypy --check-untyped-defs --follow-untyped-imports $mod_dir

